strictness: medium
test-warnings: false
doc-warnings: false
member-warnings: true

ignore-paths:
  - docs

ignore-patterns:
  - (^|/)skip(this)?(/|$)

pep8:
  full: true
  options:
    max-line-length: 121

pylint:
  disable:
    - arguments-differ

uses:
  - django

inherits:
  - strictness_medium
  - full_pep8

mccabe:
  run: true

pyroma:
  run: true
