strictness: medium
test-warnings: false
doc-warnings: false
member-warnings: true

ignore-paths:
  - docs
  - cinemanio/migration/management
  - cinemanio/settings_migration.py

ignore-patterns:
  - (^|/)skip(this)?(/|$)

pep8:
  full: true
  options:
    max-line-length: 121

pylint:
  disable:
    - arguments-differ
    - too-many-branches
    - too-many-arguments
    - logging-fstring-interpolation  # wait for https://github.com/PyCQA/pylint/issues/2395
    - cyclic-import  # possibly because https://github.com/PyCQA/pylint/issues/850

uses:
  - django

inherits:
  - strictness_medium
  - full_pep8

mccabe:
  run: true

pyroma:
  run: false
