language: python
python:
  - "3.6"
install:
  - pip install pip-compile-multi prospector
  - pip install -r requirements/dev.txt
  - pip freeze
before_script:
  - python manage.py collectstatic
script:
  - flake8 ./cinemanio
#  - prospector .
  - mypy -p cinemanio
  - bandit -r cinemanio
  - coverage run --source=cinemanio manage.py test --settings=cinemanio.settings_test
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - ramusus@gmail.com
    on_success: change
    on_failure: change
