language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --dev
before_script:
  - flake8 ./cinemanio
  - prospector -0 .
  - python manage.py collectstatic
script:
  - coverage run --source=cinemanio manage.py test --settings=cinemanio.settings_test
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - ramusus@gmail.com
    on_success: change
    on_failure: change
