language: python
python:
  - "3.6"
install:
  - pip install pipenv django==2.1.8 # prospector
  - pipenv sync --dev --sequential --three
  - pipenv graph
before_script:
  - python manage.py collectstatic
script:
  - flake8 ./cinemanio
#  - prospector .
  - mypy -p cinemanio
  - bandit -r .
  - coverage run --source=cinemanio manage.py test --settings=cinemanio.settings_test
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - ramusus@gmail.com
    on_success: change
    on_failure: change
