language: python
python:
  - "3.6"
install:
  - pip install astroid==2.0.4 certifi==2018.11.29 dodgy==0.1.9 isort==4.3.4 lazy-object-proxy==1.3.1 mccabe==0.6.1 pep8-naming==0.4.1 pipenv==2018.11.26 prospector==1.1.6.2 pycodestyle==2.4.0 pydocstyle==3.0.0 pyflakes==1.6.0 pylint==2.1.1 pylint-celery==0.3 pylint-django==2.0.2 pylint-flask==0.5 pylint-plugin-utils==0.4 pyyaml==3.13 requirements-detector==0.6 setoptconf==0.2.0 snowballstemmer==1.2.1 typed-ast==1.3.0 virtualenv==16.3.0 virtualenv-clone==0.5.1 wrapt==1.11.1
  # prospector
  - pipenv sync --dev
  - pipenv install django==2.1.8
  - pipenv graph
before_script:
  - python manage.py collectstatic
script:
  - flake8 ./cinemanio
#  - prospector .
  - mypy -p cinemanio
  - bandit -r .
  - coverage run --source=cinemanio manage.py test --settings=cinemanio.settings_test
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - ramusus@gmail.com
    on_success: change
    on_failure: change
