# Generated by Django 2.0.1 on 2018-02-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180226_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='Code'),
        ),
    ]
