# Generated by Django 2.0.1 on 2018-04-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180226_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(to='core.Role', verbose_name='Roles'),
        ),
    ]
