# Generated by Django 2.1.8 on 2019-10-11 21:47

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180919_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cast',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, help_text='Year in between 1894 and 2029', null=True, validators=[django.core.validators.MinValueValidator(1894), django.core.validators.MaxValueValidator(2029)], verbose_name='Year'),
        ),
    ]
