# Generated by Django 2.1.8 on 2019-10-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191016_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='name',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Role name'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Role name'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Role name'),
        ),
    ]
