# Generated by Django 2.1.8 on 2019-10-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191017_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='sources',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Sources'),
        ),
    ]
