# Generated by Django 2.0.8 on 2018-08-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoisk', '0002_auto_20180206_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinopoiskmovie',
            name='synced_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Synced at'),
        ),
        migrations.AddField(
            model_name='kinopoiskperson',
            name='synced_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Synced at'),
        ),
    ]
