# Generated by Django 2.0.1 on 2018-01-28 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieAttitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav', models.BooleanField(db_index=True, default=False, verbose_name='Fav')),
                ('like', models.BooleanField(db_index=True, default=False, verbose_name='Like')),
                ('seen', models.BooleanField(db_index=True, default=False, verbose_name='Have watched')),
                ('dislike', models.BooleanField(db_index=True, default=False, verbose_name='Dislike')),
                ('want', models.BooleanField(db_index=True, default=False, verbose_name='Want to watch')),
                ('ignore', models.BooleanField(db_index=True, default=False, verbose_name="Don't want to watch")),
                ('have', models.BooleanField(db_index=True, default=False, verbose_name='Have in collection')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attitudes', to='core.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovieAttitudeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favs_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('likes_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('seens_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('dislikes_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('wants_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('ignores_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('haves_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attitudes_count', to='core.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='PersonAttitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav', models.BooleanField(db_index=True, default=False, verbose_name='Fav')),
                ('like', models.BooleanField(db_index=True, default=False, verbose_name='Like')),
                ('dislike', models.BooleanField(db_index=True, default=False, verbose_name='Dislike')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attitudes', to='core.Person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonAttitudeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favs_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('likes_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('dislikes_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attitudes_count', to='core.Person')),
            ],
        ),
        migrations.CreateModel(
            name='UserAttitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.BooleanField(db_index=True, default=False, verbose_name='Friend')),
                ('expert', models.BooleanField(db_index=True, default=False, verbose_name='Expert')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attitudes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAttitudeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('experts_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attitudes_count', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userattitude',
            unique_together={('object', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='personattitude',
            unique_together={('object', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='movieattitude',
            unique_together={('object', 'user')},
        ),
    ]
