# Generated by Django 2.0.8 on 2018-08-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikipedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipediapage',
            name='content',
            field=models.TextField(blank='', default='', verbose_name='Content'),
        ),
    ]
