# Generated by Django 2.0.8 on 2018-08-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikipedia', '0002_wikipediapage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipediapage',
            name='synced_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Synced at'),
        ),
    ]
