# Generated by Django 2.0.8 on 2018-08-05 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wikipedia', '0003_wikipediapage_synced_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wikipediapage',
            unique_together={('lang', 'name'), ('content_type', 'object_id', 'lang')},
        ),
    ]
