# Generated by Django 2.0.1 on 2018-01-28 02:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attitudes', '0001_initial'),
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='familiar_movies',
            field=models.ManyToManyField(related_name='attitudes_users', through='attitudes.MovieAttitude', to='core.Movie', verbose_name='Attitudes'),
        ),
        migrations.AddField(
            model_name='user',
            name='familiar_persons',
            field=models.ManyToManyField(related_name='attitudes_users', through='attitudes.PersonAttitude', to='core.Person', verbose_name='Attitudes'),
        ),
        migrations.AddField(
            model_name='user',
            name='familiar_users_back',
            field=models.ManyToManyField(related_name='familiar_users', through='attitudes.UserAttitude', to=settings.AUTH_USER_MODEL, verbose_name='Attitudes'),
        ),
    ]
