# Generated by Django 2.0.1 on 2018-02-10 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0002_auto_20180204_1835")]

    operations = [migrations.RemoveField(model_name="user", name="types")]
