# Generated by Django 2.0.1 on 2018-02-11 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0003_remove_user_types")]

    operations = [
        migrations.RemoveField(model_name="user", name="email_about_answers"),
        migrations.RemoveField(model_name="user", name="email_about_comments"),
        migrations.RemoveField(model_name="user", name="email_about_listlinks"),
        migrations.RemoveField(model_name="user", name="email_super_listlinks"),
        migrations.RemoveField(model_name="user", name="email_super_objects_changes"),
        migrations.RemoveField(model_name="user", name="email_super_objects_comments"),
    ]
