# Generated by Django 2.0.1 on 2018-01-26 01:06

import cinemanio.sites.imdb.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImdbMovie',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='IMDb ID')),
                ('rating', models.FloatField(blank=True, db_index=True, null=True, verbose_name='IMDb rating')),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imdb', to='core.Movie')),
            ],
            bases=(models.Model, cinemanio.sites.imdb.models.UrlMixin),
        ),
        migrations.CreateModel(
            name='ImdbPerson',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='IMDb ID')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imdb', to='core.Person')),
            ],
            bases=(models.Model, cinemanio.sites.imdb.models.UrlMixin),
        ),
    ]
