# Generated by Django 2.0.1 on 2018-02-06 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180206_1854'),
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImdbCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True, verbose_name='IMDb name')),
                ('code', models.CharField(max_length=2, null=True, unique=True, verbose_name='IMDb code')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imdb', to='core.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImdbGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True, verbose_name='IMDb name')),
                ('genre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imdb', to='core.Genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImdbLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True, verbose_name='IMDb name')),
                ('code', models.CharField(max_length=2, null=True, unique=True, verbose_name='IMDb code')),
                ('language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imdb', to='core.Language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
