# Generated by Django 2.0.8 on 2018-08-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0003_imdbmovie_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='imdbmovie',
            name='synced_at',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Synced at'),
        ),
        migrations.AddField(
            model_name='imdbperson',
            name='synced_at',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Synced at'),
        ),
    ]
